[package]
name = "indexers"
version = "0.1.0"
edition = "2021"
rust-version = "1.79"

[dependencies]
ghost_crab = { git = "https://github.com/vistastaking/ghost-crab.git" }
tokio = { version = "1.37.0", features = ["full"] }
sqlx = { version = "0.7.4", features = ["runtime-tokio", "sqlite"] }
